In [ ]:
#2.20(Numpy)
#2.20.1 (Perintah Dasar pada Numpy)
import numpy as np
s_24 = np.array([0,1,2,3,4,5])
print(s_24)

[0 1 2 3 4 5]


In [ ]:
s_24.ndim

1

In [ ]:
s_24.shape

(6,)

In [ ]:
x_24 = np.array([[2,4,6,8],[1,3,5,7]])
print(x_24)

[[2 4 6 8]
 [1 3 5 7]]


In [ ]:
x_24.ndim

2

In [ ]:
x_24.shape

(2, 4)

In [ ]:
b_24 = np.array([[[[1,2,3,4],[2,4,6,8]]],
                 [[[2,3,5,7],[1,3,5,7]]],
                 [[[3,6,9,12],[4,8,12,16]]],
                 [[[5,10,15,20],[6,12,18,24]]]])
print(b_24)

[[[[ 1  2  3  4]
   [ 2  4  6  8]]]


 [[[ 2  3  5  7]
   [ 1  3  5  7]]]


 [[[ 3  6  9 12]
   [ 4  8 12 16]]]


 [[[ 5 10 15 20]
   [ 6 12 18 24]]]]


In [ ]:
b_24.ndim

4

In [ ]:
b_24.shape

(4, 1, 2, 4)

In [ ]:
#2.20.2(Memanggil Anggota, Kolom dan Baris dengan Numpy)
m_24 = np.array([[8,9,10,11],[13,14,15,16],[18,19,20,21],[23,24,25,26]])
print(m_24)

[[ 8  9 10 11]
 [13 14 15 16]
 [18 19 20 21]
 [23 24 25 26]]


In [ ]:
m_24[1,2]

15

In [ ]:
m_24[1,:]

array([13, 14, 15, 16])

In [ ]:
m_24[0,3]

11

In [ ]:
m_24[3,1]

24

In [ ]:
m_24[1,2:3]

array([15])

In [ ]:
m_24[0,1:2]

array([9])

In [ ]:
m_24[0,1:3:2]

array([9])

In [ ]:
m_24[0,0:3:1]

array([ 8,  9, 10])

In [ ]:
m_24[0,2] = 22
print(m_24)

[[ 8  9 22 11]
 [13 14 15 16]
 [18 19 20 21]
 [23 24 25 26]]


In [ ]:
m_24[1,1] = 17
print(m_24)

[[ 8  9 22 11]
 [13 17 15 16]
 [18 19 20 21]
 [23 24 25 26]]


In [ ]:
#2.20.3 (Matrix pada Numpy)_24
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.ones((3,4,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.ones((1,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.full((5,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.random.rand(3,4)

array([[0.65080165, 0.12798109, 0.09776185, 0.36685757],
       [0.53207525, 0.0043743 , 0.82246409, 0.05799131],
       [0.6213593 , 0.06171276, 0.33633636, 0.34235171]])

In [ ]:
np.random.randint(1,15,size=(4,3))

array([[ 2, 14, 10],
       [10, 10,  6],
       [ 1,  6, 13],
       [13, 14,  9]])

In [ ]:
#Matrik ukuran 10x10
h_24 = np.zeros((10,10))
print(h_24)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
e_24 = np.identity(10)
print(e_24)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
r_24 = 5*e_24
print(r_24)

[[5. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5.]]


In [ ]:
l_24 = np.ones((8,8))
i_24 = np.identity(8)*7
n_24 = l_24+i_24
print(n_24)

[[8. 1. 1. 1. 1. 1. 1. 1.]
 [1. 8. 1. 1. 1. 1. 1. 1.]
 [1. 1. 8. 1. 1. 1. 1. 1.]
 [1. 1. 1. 8. 1. 1. 1. 1.]
 [1. 1. 1. 1. 8. 1. 1. 1.]
 [1. 1. 1. 1. 1. 8. 1. 1.]
 [1. 1. 1. 1. 1. 1. 8. 1.]
 [1. 1. 1. 1. 1. 1. 1. 8.]]


In [ ]:
e_24[0:-2,1:-1] = n_24
print(e_24)

[[1. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 8. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 8. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 8. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 8. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 8. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 8. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
e_24[1:-1,1:-1] = n_24
print(e_24)

[[1. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 8. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 8. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 8. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 8. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 8. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 8. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
a_24 = np.identity(6)*9
e_24[2:-2,2:-2] = a_24
print(e_24)

[[1. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 9. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 9. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 9. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 9. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
c_24 = np.ones((4,4))*3
d_24 = np.identity(4)*2
f_24 = c_24 + d_24
print(f_24)

[[5. 3. 3. 3.]
 [3. 5. 3. 3.]
 [3. 3. 5. 3.]
 [3. 3. 3. 5.]]


In [ ]:
e_24[3:-3,3:-3] = 1
print(e_24)

[[1. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
g_24 = np.identity(2)*7
e_24[4:-4,4:-4]
print(e_24)

[[1. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 8. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
#2.20.4 Copy pada Numpy
h_24 = np.array([2,3,5,7,11])
print(h_24)

[ 2  3  5  7 11]


In [ ]:
j_24 = h_24
print(j_24)

[ 2  3  5  7 11]


In [ ]:
j_24[2] = 20
print(j_24)

[ 2  3 20  7 11]


In [ ]:
print(h_24)

[ 2  3 20  7 11]


In [ ]:
k_24 = np.array([20,22,24,26])
print(k_24)

[20 22 24 26]


In [ ]:
o_24 = k_24.copy()
print(o_24)

[20 22 24 26]


In [ ]:
print(k_24)

[20 22 24 26]


In [ ]:
#2.20.5 Operasi Matematika pada Numpy
b_24+4

array([[[[ 5,  6,  7,  8],
         [ 6,  8, 10, 12]]],


       [[[ 6,  7,  9, 11],
         [ 5,  7,  9, 11]]],


       [[[ 7, 10, 13, 16],
         [ 8, 12, 16, 20]]],


       [[[ 9, 14, 19, 24],
         [10, 16, 22, 28]]]])

In [ ]:
k_24-3

array([17, 19, 21, 23])

In [ ]:
j_24*5

array([ 10,  15, 100,  35,  55])

In [ ]:
k_24/2

array([10., 11., 12., 13.])

In [ ]:
k_24**2

array([400, 484, 576, 676])

In [ ]:
p_24 = np.array([1,2,3,4,5])
print(p_24)

[1 2 3 4 5]


In [ ]:
k_24+b_24

array([[[[21, 24, 27, 30],
         [22, 26, 30, 34]]],


       [[[22, 25, 29, 33],
         [21, 25, 29, 33]]],


       [[[23, 28, 33, 38],
         [24, 30, 36, 42]]],


       [[[25, 32, 39, 46],
         [26, 34, 42, 50]]]])

In [ ]:
np.cos (p_24)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [ ]:
np.sin(p_24)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [ ]:
np.tan(p_24)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [ ]:
np.sinh(p_24)

array([ 1.17520119,  3.62686041, 10.01787493, 27.2899172 , 74.20321058])

In [ ]:
np.cosh(p_24)

array([ 1.54308063,  3.76219569, 10.067662  , 27.30823284, 74.20994852])

In [ ]:
np.tanh(p_24)

array([0.76159416, 0.96402758, 0.99505475, 0.9993293 , 0.9999092 ])

In [ ]:
np.sqrt(p_24)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
#2.20.6 Perkalian Matrik pada Numpy
y_24 = np.array([[2,4,6,8],[1,3,5,7]])
print(y_24)

[[2 4 6 8]
 [1 3 5 7]]


In [ ]:
q_24 = np.array([[2,3,5,7],[7,8,9,10]])
print(q_24)

[[ 2  3  5  7]
 [ 7  8  9 10]]


In [ ]:
w_24 = y_24*q_24
print(w_24)

[[ 4 12 30 56]
 [ 7 24 45 70]]


In [ ]:
r_24 = y_24+q_24
print(r_24)

[[ 4  7 11 15]
 [ 8 11 14 17]]


In [ ]:
t_24 = r_24**2
print(t_24)

[[ 16  49 121 225]
 [ 64 121 196 289]]


In [ ]:
#2.20.7 min, max dan sum pada Numpy
s_24 = np.array([[12,14,16,18],
                 [22,24,26,28],
                 [32,34,36,38]])
print(s_24)

[[12 14 16 18]
 [22 24 26 28]
 [32 34 36 38]]


In [ ]:
z_24 = np.min(s_24)
print(z_24)

12


In [ ]:
v_24 = np.min(s_24,axis=1)
print(v_24)

[12 22 32]


In [ ]:
va_24 = np.min(s_24,axis=0)
print(va_24)

[12 14 16 18]


In [ ]:
se_24 = np.max(s_24)
print(se_24)

38


In [ ]:
ga_24 = np.max(s_24,axis=0)
print(ga_24)

[32 34 36 38]


In [ ]:
ge_24 = np.max(s_24,axis=1)
print(ge_24)

[18 28 38]


In [ ]:
ha_24 = np.sum(s_24)
print(ha_24)

300


In [ ]:
ha_24 = np.sum(s_24,axis=0)
print(ha_24)

[66 72 78 84]


In [ ]:
hi_24 = np.sum(s_24,axis=1)
print(hi_24)

[ 60 100 140]
